# Minimal config for production - optimized performance
# Reduces CPU/Memory usage by disabling non-essential features

# Core trading configuration (minimal)
attention:
  learning_rate: 0.001
  min_trades_learning: 200
  min_trades_shadow: 100
  min_trades_active: 50

regime_detector:
  update_interval: 60  # 1 minute instead of real-time
  ensemble:
    enabled: false  # Disable ensemble for performance

strategy_selector:
  cross_validation: false  # Disable CV for speed

risk_management:
  max_position_size: 0.05
  max_daily_loss: 0.02
  check_interval: 30  # Check every 30 seconds

execution:
  max_orders: 50  # Reduce concurrent orders
  
performance:
  metrics_interval: 60  # 1 minute metrics
  
feedback:
  update_interval: 120  # 2 minutes feedback

# Disable expensive features
augmentation:
  enabled: false  # ปิด augmentation ใน production mode
  training_mode_default: false
  
scaling_monitor:
  enabled: false  # ปิด scaling monitor
  
# Dashboard with reduced frequency
dashboard:
  enabled: true
  update_interval: 10  # update ทุก 10 วินาที
  websocket_interval: 5
  
# Monitoring optimized
monitoring:
  health_check_interval: 60  # 1 minute
  checkpoint_interval: 300   # 5 minutes
  overfitting_check_interval: 300  # 5 minutes
  stress_test_interval: 3600  # 1 hour instead of 10 minutes
  
# Performance optimizations
performance_optimization:
  main_loop_interval: 1.0    # 1 second main loop
  monitoring_frequency: 30   # 30 seconds
  cache_ttl: 10             # 10 seconds cache
  max_workers: 2            # Limit worker threads
  
# Memory limits
memory:
  max_memory_mb: 2048       # 2GB limit
  cleanup_interval: 600     # 10 minutes
  gc_threshold: 1000        # Force GC every 1000 operations
  
# Logging
logging:
  level: WARNING  # Reduce log verbosity
  max_file_size: 100MB
  backup_count: 3