# config.yaml - Complete GridAttention Configuration
# Security: Use environment variables for production
exchanges:
  binance:
    class: "binance"
    api_key: "X91ndaroJjPpPDDCtk7B2VjnsCBynWBYWBnr2cdGkIPyyTv1qGO4RqzchTiteQIU"
    secret: "jzzEzD7aMGlAyqDUbAvC0fuLF3IWQAqY622VPHbCL8rpcQBW1DaLUnOzdK145hKj"
    rate_limit: 50
    rate_window: 1000
    websocket_url: "wss://stream.binance.com:9443/ws"
    options:
      defaultType: "spot"
system:
  mode: "paper_trading"    # paper_trading | live_trading
  capital: 10000           # เงินทุนเริ่มต้น
  base_currency: "USDT"

market_data:
  buffer_size: 1000
  attention_store_size: 10000
  websocket:
    reconnect_delay: 5
    max_reconnect_attempts: 10
  exchanges:
    - name: "binance"
      url: "wss://stream.binance.com:9443/ws"
      subscribe_msg:
        method: "SUBSCRIBE"
        params: ["btcusdt@ticker"]
        id: 1
  validators:
    price_min: 0
    price_max_change: 0.1
    volume_min: 0
    volume_max_spike: 10.0
    timestamp_max_delay: 1000
features:
  technical_indicators:
    - rsi
    - sma
    - ema
    - bollinger_bands
  lookback_periods: [14, 20, 50]

attention:
  min_trades_learning: 1000
  min_trades_shadow: 200
  min_trades_active: 100
  control_percentage: 0.3

regime_detector:
  volatility_window: 20
  trend_window: 50
  correlation_threshold: 0.7

strategy_selector:
  grid_types: ["symmetric", "geometric"]
  spacing_range: [0.001, 0.01]
  level_range: [3, 10]

risk_management:
  max_position_size: 0.1  # 10% of capital
  max_daily_loss: 0.05    # 5% daily loss limit
  max_drawdown: 0.15      # 15% drawdown limit
  stop_loss: 0.02         # 2% stop loss
  take_profit: 0.04       # 4% take profit

execution:
  binance:
    class: "binance"
    api_key: "X91ndaroJjPpPDDCtk7B2VjnsCBynWBYWBnr2cdGkIPyyTv1qGO4RqzchTiteQIU"
    secret: "jzzEzD7aMGlAyqDUbAvC0fuLF3IWQAqY622VPHbCL8rpcQBW1DaLUnOzdK145hKj"
    rate_limit: 50
    rate_window: 1000
    options:
      defaultType: "spot"
performance:
  metrics_interval: 60     # seconds
  report_interval: 3600    # 1 hour
  save_interval: 86400     # 24 hours

# Priority 1-2 Fixes Configuration
memory:
  max_memory_percent: 80
  cleanup_interval: 300      # 5 minutes
  auto_cleanup: true
  retention_hours: 24

validation:
  enable_validation: true
  feature_validation: true
  order_validation: true
  data_integrity_checks: true
  anomaly_threshold: 4       # standard deviations

error_recovery:
  max_retry_attempts: 3
  initial_delay: 1.0
  max_delay: 60.0
  circuit_breaker_threshold: 5
  recovery_timeout: 60

performance_optimization:
  enable_caching: true
  cache_size: 1000
  cache_ttl: 300             # 5 minutes
  use_optimized_calculator: true
  batch_processing: true
  batch_size: 50

feedback:
  learning_rate: 0.01
  adaptation_speed: "medium"

logging:
  level: "INFO"
  file: "grid_trading.log"
  max_size: "50MB"  # Increased from 10MB
  backup_count: 10  # Increased from 5
  rotation: "time"  # Add time-based rotation
  rotation_interval: "daily"  # Daily rotation
  compression: "gzip"  # Compress old logs
  
  # Alternative log destinations
  console_output: true
  error_file: "grid_trading_errors.log"
  
  # Log filtering
  filters:
    - name: "trading_only"
      level: "INFO"
      modules: ["execution", "risk_management", "performance"]
    - name: "debug_augmentation"
      level: "DEBUG"
      modules: ["augmentation", "attention"]
      
  # Performance settings
  buffer_size: 1000  # Buffer logs for better performance
  flush_interval: 5  # Flush every 5 seconds

# Scaling Monitor Configuration
scaling_monitor:
  # Thresholds for alerts
  thresholds:
    cpu_warning: 70.0
    cpu_critical: 90.0
    memory_warning: 80.0
    memory_critical: 95.0
    latency_warning: 20.0  # ms
    latency_critical: 50.0  # ms
    queue_warning: 500
    queue_critical: 1000
    error_rate_warning: 0.01  # 1%
    error_rate_critical: 0.05  # 5%
    # New: Log file size monitoring
    log_size_warning: "100MB"
    log_size_critical: "500MB"
    disk_space_warning: 85.0  # %
    disk_space_critical: 95.0  # %
    
  # Auto-scaling configuration
  auto_scaling:
    enabled: false
    cooldown_seconds: 300  # 5 minutes between scaling actions
    
  # Monitoring intervals
  check_interval: 60  # seconds
  report_interval: 300  # 5 minutes
  log_check_interval: 300  # Check log sizes every 5 minutes

  # Export settings
  export_metrics: true
  export_path: "./metrics_export/"
  
  # Log management
  log_management:
    auto_cleanup: true
    max_total_log_size: "1GB"
    cleanup_older_than: "30d"  # Delete logs older than 30 days

# Phase-Aware Data Augmentation
augmentation:
  enabled: true
  training_mode_default: true  # Default to training mode
  
  # Phase-specific configurations
  phases:
    learning:
      enabled: true
      augmentation_factor: 3.0  # 3x original data
      methods:
        - noise_injection
        - time_warping
        - magnitude_warping
        - bootstrap_sampling
        - synthetic_patterns
        - feature_dropout
      noise_level: moderate
      preserve_correlations: true
      
    shadow:
      enabled: true
      augmentation_factor: 1.5  # 1.5x original data
      methods:
        - noise_injection
        - bootstrap_sampling
      noise_level: conservative
      preserve_correlations: true
      
    active:
      enabled: false  # Disabled by default in production
      augmentation_factor: 1.0  # No augmentation
      methods: []
      noise_level: none
      emergency_augmentation: true  # Enable if performance drops
      
  # Augmentation scheduler settings
  scheduler:
    performance_thresholds:
      min_win_rate: 0.45
      min_sharpe_ratio: 0.5
    degradation_detection:
      enabled: true
      window_size: 1000
      threshold: 0.1
    adaptive_factor:
      enabled: true
      min_factor: 1.0
      max_factor: 3.0
      
  # Quality control
  quality:
    min_quality_score: 0.8
    correlation_preservation_threshold: 0.2
    distribution_test_threshold: 0.2
    
  # Statistics and monitoring
  monitoring:
    enabled: true
    window_size: 1000  # Number of events to track
    log_interval: 300  # seconds
    save_stats_interval: 3600  # seconds
    alert_on_active_augmentation: true
    dashboard_enabled: true
    alert_check_interval: 60  # Check alerts every minute
    
    # Alert thresholds
    alerts:
      active_phase_augmentation: true
      low_quality_threshold: 0.7
      excessive_factor_threshold: 5.0
    
    # Statistics collection
    statistics:
      track_methods: true
      track_quality: true
      track_performance_correlation: true
