# Production Configuration for GridAttention Trading System
# Optimized for stability, performance, and resource efficiency

mode: production
environment: production

# Core trading configuration (production-optimized)
attention:
  learning_rate: 0.0001  # Conservative learning rate
  min_trades_learning: 500  # More data required before transitioning
  min_trades_shadow: 200
  min_trades_active: 100
  regularization_strength: 0.3  # Higher regularization
  dropout_rate: 0.2
  batch_size: 32  # Smaller batches for memory efficiency

regime_detector:
  update_interval: 300  # 5 minutes instead of real-time
  ensemble:
    enabled: true  # Keep ensemble for accuracy
    models: 3  # Reduced from 5 to 3 models
  confidence_threshold: 0.8  # Higher confidence required
  
strategy_selector:
  cross_validation: true  # Keep validation for safety
  validation_splits: 3  # Reduced from 5 splits
  max_strategies: 5  # Limit concurrent strategies
  
risk_management:
  max_position_size: 0.03  # Conservative 3% max position
  max_daily_loss: 0.01  # 1% daily loss limit
  max_total_exposure: 0.15  # 15% total exposure
  check_interval: 60  # Check every minute
  emergency_stop_loss: 0.05  # 5% emergency stop
  
execution:
  max_orders: 20  # Reduced concurrent orders
  order_timeout: 30  # 30 second timeout
  retry_attempts: 2  # Reduced retries
  latency_threshold: 1000  # 1 second max latency

# Performance monitoring (optimized)
performance:
  metrics_interval: 300  # 5 minute metrics
  stress_test_interval: 7200  # 2 hours stress tests
  max_performance_history: 50000  # Limit history size
  
feedback:
  update_interval: 600  # 10 minutes feedback (very conservative)
  min_samples: 1000  # More samples required
  adjustment_cooldown: 3600  # 1 hour cooldown between adjustments
  max_adjustment_rate: 0.02  # 2% max adjustment

# Disable expensive features in production
augmentation:
  enabled: false  # Completely disabled in production
  training_mode_default: false
  
scaling_monitor:
  enabled: false  # Disable scaling monitor for performance
  
# Unified monitoring configuration
monitoring:
  unified_monitor:
    enabled: true
    health_check_interval: 300  # 5 minutes
    performance_interval: 60   # 1 minute
    checkpoint_interval: 3600  # 1 hour
    overfitting_interval: 300  # 5 minutes
    augmentation_interval: 600 # 10 minutes (disabled anyway)
    resource_check_interval: 180  # 3 minutes
  
  # Individual loop settings (fallback)
  health_check_interval: 300
  checkpoint_interval: 3600
  overfitting_check_interval: 300
  
# Dashboard configuration (performance optimized)
dashboard:
  enabled: true
  update_interval: 30  # 30 seconds updates
  websocket_interval: 15  # 15 seconds websocket
  cache_ttl: 20  # 20 seconds cache
  max_query_size: 500  # Limit query results
  timeout_seconds: 5  # 5 second query timeout
  pagination:
    default_page_size: 50
    max_page_size: 200
  
# Data retention limits
data_retention:
  market_data_buffer: 5000  # 5K market data points
  performance_history: 20000  # 20K performance records
  trade_history: 50000  # 50K trade records
  log_retention_hours: 168  # 1 week
  checkpoint_retention_days: 30
  
# Memory management
memory:
  max_memory_mb: 1536  # 1.5GB limit for production
  cleanup_interval: 300  # 5 minutes automatic cleanup
  gc_threshold: 500  # Force GC every 500 operations
  emergency_cleanup_threshold: 0.9  # 90% memory usage
  
  # Buffer limits
  buffers:
    market_data: 5000
    performance: 20000
    trades: 50000
    logs: 1000
    features: 10000

# Resource limits
resources:
  max_cpu_cores: 2
  process_priority: 10  # Normal priority
  max_open_files: 1024
  max_threads: 20
  
# Performance optimization
performance_optimization:
  main_loop_interval: 2.0  # 2 seconds main loop (slower for stability)
  monitoring_frequency: 60  # 1 minute monitoring
  cache_ttl: 30  # 30 seconds cache
  max_workers: 2
  batch_processing: true
  async_optimization: true
  
# Logging (production optimized)
logging:
  level: WARNING  # Reduce log verbosity
  max_file_size: 50MB
  backup_count: 5
  log_to_file: true
  log_to_console: false  # Disable console logging
  structured_logging: true
  
# API configuration
api:
  enabled: true
  port: 8080
  rate_limit: 100  # requests per minute
  timeout: 10  # seconds
  authentication: true
  
# Database settings (if applicable)
database:
  connection_pool_size: 5
  query_timeout: 10
  max_connections: 10
  
# Security settings
security:
  api_key_required: true
  rate_limiting: true
  input_validation: strict
  sanitize_logs: true
  
# Alerting configuration
alerts:
  enabled: true
  email_enabled: false  # Disable email for now
  webhook_enabled: true
  alert_cooldown: 300  # 5 minutes between same alerts
  
  thresholds:
    high_memory_usage: 0.85  # 85%
    high_cpu_usage: 0.80     # 80%
    low_disk_space: 0.90     # 90%
    high_error_rate: 0.05    # 5%
    low_win_rate: 0.35       # 35%
    high_drawdown: 0.08      # 8%

# Backup and recovery
backup:
  enabled: true
  checkpoint_interval: 3600  # 1 hour
  backup_retention_days: 7
  auto_recovery: true
  
# Feature flags
features:
  warmup_system: false  # Skip warmup in production
  experimental_features: false
  debug_mode: false
  profiling: false
  metrics_export: true
  
# Prometheus metrics
prometheus:
  enabled: true
  port: 9090
  scrape_interval: 30
  
# Health check endpoints
health_check:
  enabled: true
  port: 8081
  endpoints:
    - /health
    - /ready
    - /metrics
    
# Circuit breaker settings
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 60
  half_open_max_calls: 3
  
# Retry configuration
retry:
  max_attempts: 3
  base_delay: 1.0
  max_delay: 10.0
  exponential_base: 2.0